# -*- coding: utf-8 -*-
"""
/***************************************************************************
 JMATilesLoader
                                 A QGIS plugin
 Dynamic layer loader of JMA Tiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-16
        copyright            : (C) 2024 by mugwort_rc
        email                : mugwort.rc@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load JMATilesLoader class from file JMATilesLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .jma_tiles_loader import JMATilesLoader
    return JMATilesLoader(iface)
